

ffmpeg_path = '/home/evg/Downloads/ffmpeg';

inDirPaths = {...'/media/evg/WinHome/LBMV-project/videoData/src/Everton_Chelsea_14_September_2013', ...
              ...'/media/evg/WinHome/LBMV-project/videoData/src/Everton_Chelsea_14_September_2013', ...
              ...'/media/evg/WinHome/LBMV-project/videoData/src/Chelsea-Everton-19.05.13', ...
              ...'/media/evg/WinHome/LBMV-project/videoData/src/Chelsea-Everton-19.05.13', ...
              ...'/media/evg/WinHome/LBMV-project/videoData/src/Manchester_United_vs_Manchester_City_720p', ...
              ...'/media/evg/WinHome/LBMV-project/videoData/src/Manchester_United_vs_Manchester_City_720p', ...
              ...'/media/evg/WinHome/LBMV-project/videoData/src/Man_City_Man_Utd_22_September_2013', ...
              ...'/media/evg/WinHome/LBMV-project/videoData/src/Man_Utd_Crystal_Palace_14_September_2013', ...
              ...'/media/evg/WinHome/LBMV-project/videoData/src/Sunderland_Arsenal_14_September_2013', ...
              ...'/media/evg/WinHome/LBMV-project/videoData/src/Tottenham_Norwich_14_September_2013', ...
              '/media/evg/WinHome/LBMV-project/videoData/src/EPL.2013.05.19.Newcastle.Vs.Arsenal.720p.HDTV.x264-FAIRPLAY', ...
              '/media/evg/WinHome/LBMV-project/videoData/src/EPL.2013.08.17.Swansea.City.vs.Manchester.United.720p.HDTV.x264-PRiNCE', ...
              '/media/evg/WinHome/LBMV-project/videoData/src/EPL.2013.09.16.Swansea.City.Vs.Liverpool.720p.HDTV.x264-FAIRPLAY', ...
              '/media/evg/WinHome/LBMV-project/videoData/src/wrong-Man_Utd_Chelsea_26_August_2013'...
             };
         
inVideoNames = {...'Everton-Chelsea-EPL13-1.mkv', ...
                ...'Everton-Chelsea-EPL13-2.mkv', ...
                ...'Chelsea-Everton-May2013-1.mkv', ...
                ...'Chelsea-Everton-May2013-2.mkv', ...
                ...'MNU-MCity-EPL13-1.mkv', ...
                ...'MNU-MCity-EPL13-1.mkv', ...
                ...'MCity-MNU-EPL13.mkv', ...
                ...'MNU-CrPal-EPL13.mkv', ...
                ...'Sunderland-Arsenal-EPL13.mkv', ...
                ...'Tottenham-Norwich.mkv', ...
                'fairplay-epl.2013.05.19.newcastle.vs.arsenal.720p.mkv', ...
                'epl.2013.08.17.swansea.city.vs.manchester.united.720p.hdtv.x264-prince.mkv', ...
                'fairplay-epl.2013.09.16.swansea.vs.liverpool.720p.mkv', ...
                'MNU-Chelsea-EPL13.mkv'...
               };


for i = 1 : length(inDirPaths)
    
    inDirPath = char(inDirPaths{i});
    inVideoName =  char(inVideoNames{i});
    [~,name,~] = fileparts(inVideoName);

    outDirPath = fullfile(inDirPath, 'shots');
    histDiffName = strcat(name, '-hist_diff.txt');    
    histPeaksName =  strcat(name, '-hist_peaks.txt');
    shotsNamePrefix = strcat(name, '-');

    fprintf ('%s \n', inVideoName);
    
%     command = strcat ('getHistDiff/bin/getHistDiff', ...
%                       ' -i', {' '}, fullfile(inDirPath, inVideoName), ...
%                       ' -o', {' '}, fullfile(inDirPath, histDiffName));
%                   
%     [status, stdout] = system(char(command));
%     if status ~= 0
%         fprintf ('%s \n', stdout);
%         error ('Error in system(getHistDiff)');
%     end
         
     cutIntoShots (inDirPath, histDiffName, inVideoName, ...
                   outDirPath, histPeaksName, shotsNamePrefix, ffmpeg_path);
              
end